export const users = [
  {
    role: "restaurant",
    email: "spice@bhojansetu.test",
    password: "secret123",
    profile: {
      businessName: "Spice Kitchen",
      ownerName: "Aman Mehra",
      phone: "+91 98765 43210",
      address: "Bandra West, Mumbai, Maharashtra",
      cuisine: "North Indian",
      email: "spice@bhojansetu.test",
    },
  },
  {
    role: "individual",
    email: "priya@bhojansetu.test",
    password: "secret123",
    profile: {
      name: "Priya Sharma",
      phone: "+91 91234 56789",
      location: "Andheri East, Mumbai",
      email: "priya@bhojansetu.test",
    },
  },
  {
    role: "restaurant",
    email: "royal@bhojansetu.test",
    password: "secret123",
    profile: {
      businessName: "Royal Caterers",
      ownerName: "Nikhil Rao",
      phone: "+91 99887 76655",
      address: "Powai, Mumbai, Maharashtra",
      cuisine: "Corporate Catering",
      email: "royal@bhojansetu.test",
    },
  },
  {
    role: "ngo",
    email: "contact@rotibank.org",
    password: "secret123",
    profile: {
      ngoName: "Roti Bank Foundation",
      phone: "+91 98201 11122",
      area: "Andheri West",
      cause: "Hunger relief & daily meals",
      email: "contact@rotibank.org",
    },
  },
  {
    role: "ngo",
    email: "hello@helpinghands.org.in",
    password: "secret123",
    profile: {
      ngoName: "Helping Hands Society",
      phone: "+91 91111 88899",
      area: "Powai",
      cause: "Disaster response & daily meals",
      email: "hello@helpinghands.org.in",
    },
  },
];

export const ngos = [
  {
    name: "Roti Bank Foundation",
    area: "Andheri West",
    city: "Mumbai",
    address: "Andheri West, Mumbai, Maharashtra",
    lat: 19.1363,
    lng: 72.8277,
    phone: "+91 98201 11122",
    email: "contact@rotibank.org",
    website: "https://rotibank.org",
    cause: "Hunger relief & daily meals",
    distanceKm: 1.2,
    serviceRadiusKm: 8,
    acceptedCategories: ["healthy", "normal", "junk"],
    maxPickupQuantityKg: 80,
    rating: 4.8,
    mealsServed: 124000,
    description: "Picks up surplus food from kitchens and distributes to slums in Andheri & Bandra.",
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600",
  },
  {
    name: "Feeding India - Mumbai Chapter",
    area: "Bandra East",
    city: "Mumbai",
    address: "Bandra East, Mumbai, Maharashtra",
    lat: 19.0551,
    lng: 72.8465,
    phone: "+91 98765 22233",
    email: "mumbai@feedingindia.org",
    website: "https://feedingindia.org",
    cause: "Zero hunger, child nutrition",
    distanceKm: 2.4,
    serviceRadiusKm: 12,
    acceptedCategories: ["healthy", "normal"],
    maxPickupQuantityKg: 150,
    rating: 4.9,
    mealsServed: 980000,
    description: "Pan-India movement working with restaurants and event venues to redirect surplus food.",
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600",
  },
  {
    name: "Annapurna Seva Trust",
    area: "Dadar",
    city: "Mumbai",
    address: "Dadar, Mumbai, Maharashtra",
    lat: 19.0178,
    lng: 72.8478,
    phone: "+91 99300 44455",
    email: "info@annapurnaseva.in",
    website: "https://annapurnaseva.in",
    cause: "Elderly & street children",
    distanceKm: 3.1,
    serviceRadiusKm: 10,
    acceptedCategories: ["healthy", "normal"],
    maxPickupQuantityKg: 60,
    rating: 4.7,
    mealsServed: 56000,
    description: "Daily kitchens for senior citizens and street children across central Mumbai.",
    image: "https://images.unsplash.com/photo-1593113616828-6f22bca04804?w=600",
  },
  {
    name: "Helping Hands Society",
    area: "Powai",
    city: "Mumbai",
    address: "Powai, Mumbai, Maharashtra",
    lat: 19.1176,
    lng: 72.906,
    phone: "+91 91111 88899",
    email: "hello@helpinghands.org.in",
    website: "https://helpinghands.org.in",
    cause: "Disaster response & daily meals",
    distanceKm: 4.6,
    serviceRadiusKm: 15,
    acceptedCategories: ["healthy", "normal", "junk"],
    maxPickupQuantityKg: 120,
    rating: 4.6,
    mealsServed: 38000,
    description: "Rapid pickup teams across eastern suburbs. 24x7 hotline.",
    image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=600",
  },
  {
    name: "Aahaar Daan",
    area: "Goregaon",
    city: "Mumbai",
    address: "Goregaon, Mumbai, Maharashtra",
    lat: 19.1646,
    lng: 72.8493,
    phone: "+91 90909 33344",
    email: "team@aahaardaan.org",
    website: "https://aahaardaan.org",
    cause: "Food rescue & redistribution",
    distanceKm: 5.2,
    serviceRadiusKm: 10,
    acceptedCategories: ["normal", "junk"],
    maxPickupQuantityKg: 90,
    rating: 4.5,
    mealsServed: 22000,
    description: "Volunteer-driven NGO partnering with weddings and caterers for food rescue.",
    image: "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=600",
  },
  {
    name: "Khushiyaan Foundation",
    area: "Thane",
    city: "Mumbai",
    address: "Thane West, Maharashtra",
    lat: 19.2183,
    lng: 72.9781,
    phone: "+91 92929 77788",
    email: "connect@khushiyaan.org",
    website: "https://khushiyaan.org",
    cause: "Children, education & meals",
    distanceKm: 6.8,
    serviceRadiusKm: 18,
    acceptedCategories: ["healthy", "normal"],
    maxPickupQuantityKg: 110,
    rating: 4.7,
    mealsServed: 45000,
    description: "Combines education with daily nutrition for underprivileged children in Thane.",
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600",
  },
];

export const impactStories = [
  {
    title: "A warm meal brought smiles in Andheri",
    body: "A donation of 5 kg of rice and dal was distributed to 20 families in Andheri East through Roti Bank Foundation. Volunteers shared photos of children eating their first proper dinner in days.",
    storyDate: "Yesterday",
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=900",
    source: "Roti Bank Foundation",
  },
  {
    title: "How sharing food changes lives",
    body: "Meet Ramesh, a daily wage worker who received a nutritious meal thanks to a donor like you. He says it gave him strength to go look for work the next morning.",
    storyDate: "3 days ago",
    image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=900",
    source: "Feeding India",
  },
  {
    title: "100 meals shared this month in Mumbai",
    body: "Together, donors in Mumbai have shared over 100 meals this month alone. The momentum is building and every plate counts.",
    storyDate: "1 week ago",
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=900",
    source: "BhojanSetu Network",
  },
  {
    title: "Wedding leftovers feed 200 children",
    body: "A South Mumbai wedding party donated their entire surplus buffet. Two hundred children at a Dadar shelter had a full dinner that night.",
    storyDate: "2 weeks ago",
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=900",
    source: "Annapurna Seva Trust",
  },
];

export const donations = [
  {
    donorEmail: "spice@bhojansetu.test",
    donorType: "restaurant",
    donorName: "Spice Kitchen",
    donorPhone: "+91 98765 43210",
    donorLocation: "Bandra West, Mumbai",
    pickupAddress: "Bandra West, Mumbai, Maharashtra",
    pickupLat: 19.0596,
    pickupLng: 72.8295,
    totalPrepared: "120 kg",
    remaining: "18 kg",
    category: "healthy",
    description: "Veg biryani, dal makhani, and roti packed and ready for pickup.",
    photo: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    status: "pending",
    fulfillmentType: null,
    ngoActionHistory: [],
  },
  {
    donorEmail: "priya@bhojansetu.test",
    acceptedByNgoEmail: "contact@rotibank.org",
    donorType: "individual",
    donorName: "Priya Sharma",
    donorPhone: "+91 91234 56789",
    donorLocation: "Andheri East, Mumbai",
    pickupAddress: "Andheri East, Mumbai, Maharashtra",
    pickupLat: 19.1136,
    pickupLng: 72.8697,
    totalPrepared: "Wedding party - 200 plates",
    remaining: "35 plates",
    category: "normal",
    description: "Paneer curry, jeera rice, salad and sweets from a wedding reception.",
    photo: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600",
    status: "in_transit",
    fulfillmentType: "pickup",
    acceptedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    ngoActionHistory: [
      { action: "accepted", actorRole: "ngo", status: "accepted", createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString() },
      { action: "fulfillment_selected", actorRole: "ngo", status: "in_transit", fulfillmentType: "pickup", createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString() },
    ],
    rating: 5,
  },
  {
    donorEmail: "royal@bhojansetu.test",
    acceptedByNgoEmail: "hello@helpinghands.org.in",
    donorType: "restaurant",
    donorName: "Royal Caterers",
    donorPhone: "+91 99887 76655",
    donorLocation: "Powai, Mumbai",
    pickupAddress: "Powai, Mumbai, Maharashtra",
    pickupLat: 19.1176,
    pickupLng: 72.906,
    totalPrepared: "300 kg corporate lunch",
    remaining: "42 kg",
    category: "normal",
    description: "Mixed Indian thali items in sealed containers, fresh from this afternoon.",
    photo: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600",
    status: "delivered",
    fulfillmentType: "delivery",
    acceptedAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    completionConfirmed: true,
    deliveryConfirmedByNgo: true,
    completionNote: "Meals were redistributed to the evening shelter route in Powai.",
    ngoActionHistory: [
      { action: "accepted", actorRole: "ngo", status: "accepted", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString() },
      { action: "fulfillment_selected", actorRole: "ngo", status: "in_transit", fulfillmentType: "delivery", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 19).toISOString() },
      { action: "completed", actorRole: "ngo", status: "delivered", fulfillmentType: "delivery", note: "Meals were redistributed to the evening shelter route in Powai.", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString() },
    ],
    rating: 4,
  },
];
